version: "3.8"

services:
  php:
    container_name: ivyshop.api
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - .:/app:delegated
    ports:
      - "8040:8040"
      - "9040:9001"
    command: symfony serve --port=8040
    networks:
      - ivyshop

  db:
    container_name: ivyshop.db
    image: postgres:16.0
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DB: ivyshop
      POSTGRES_USER: roger.dev
      POSTGRES_PASSWORD: psw1234
    ports:
      - "54320:5432"
    networks:
      - ivyshop

networks:
  ivyshop:
