name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.26.0
        with:
          php-version: '8.2-fpm'

      - name: Composer install
        run: composer install

      - name: Php CS Fixer
        run: make lint
